### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by ByronComparisonTech** [wavefrontHQ/wavefront-appmetrics-sdk-csharp#30]
Running the proxy method, and the App Metrics IHostBuilder extensions in .NET Core 3.1 I get the following exception.

System.TypeLoadException: 'Method 'Write' in type 'App.Metrics.Formatters.Wavefront.MetricSnapshotWavefrontWriter' from assembly 'Wavefront.AppMetrics.SDK.CSharp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by hanwavefront** [comment]
@ByronComparisonTech What version of App Metrics are you using?

**Comment by ByronComparisonTech** [comment]
@hanwavefront The latest stable version, 4.0.0

**Comment by hanwavefront** [comment]
@ByronComparisonTech Thanks for pointing this out. We've made a release (https://www.nuget.org/packages/Wavefront.AppMetrics.SDK.CSharp/3.0.0) that supports App Metrics 4.x.
